#!/bin/bash

#upgrade
#find . -type f -iname "*.java" -exec sed -i 's/This is the source code of Telegram for Android/This is the source code of Telegrog for Android/g' "{}" +;
#find . -type f -iname "*.xml" -exec sed -i 's/This is the source code of Telegram for Android/This is the source code of Telegrog for Android/g' "{}" +;

#revert
#find . -type f -iname "*.java" -exec sed -i 's/This is the source code of Telegrog for Android/This is the source code of Telegram for Android/g' "{}" +;
#find . -type f -iname "*.xml" -exec sed -i 's/This is the source code of Telegrog for Android/This is the source code of Telegram for Android/g' "{}" +;
